10307 - don't show sticky newsletter sign up button if 'tito' is presented in url query param
MozillaFoundation/foundation.mozilla.org pull request #10308
Opened 2023-03-08 18:25 UTC by mmmavis

Related PRs/issues: #10307

- Go to http://mozfest.localhost:8000/en/newsletter/ on a smaller screen and see if sticky button is gone
- Click on "secure your ticket". Make sure you are able to access full content in the Tito popup.

2023-03-08 18:49 UTC, danielfmiranda requested changes
Hi @mmmavis! 

This works great for the initial sign up form, however, once you follow the sign up flow to the "assign your tickets" page, the "Sign Up" button appears to cover the buttons at the bottom of the modal again:
<img width="451" alt="Screenshot 2023-03-08 at 10 44 58 AM" src="https://user-images.githubusercontent.com/18314510/223807036-0e19fa01-0c00-47fb-9ee4-4fd34c95d3ec.png">

2023-03-09 06:46 UTC, mmmavis commented on source/js/foundation/pages/mozfest/tito.js
> - * Using the tito library to set up a ticket purchasing widget.
This file didn't seem to be used/imported anywhere in the codebase. I'm reviving it.

2023-03-09 06:50 UTC, mmmavis commented
@danielfmiranda thanks for catching the bug. I realized Tito API has something we could utilize so I went with that route instead of my original approach.

2023-03-09 20:52 UTC, danielfmiranda approved these changes
Thanks @mmmavis! The latest changes look good to me

2023-03-09 20:52 UTC, merged