Rename two petition snippet fields and add a new field
MozillaFoundation/foundation.mozilla.org pull request #10961
Opened 2023-08-03 19:04 UTC by mmmavis

# Description

Link to sample test page:
Related PRs/issues: #

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2023-08-08 10:55 UTC, jhonatan-lopes requested changes
Hi @mmmavis! It's all looking good, I just have some comments

2023-08-08 18:04 UTC, mmmavis commented on network-api/networkapi/wagtailpages/migrations/0096_map_petition_comment_value.py
> +        petition.save()
Thanks for the great suggestion! Didn't know this existed until now!

2023-08-08 18:07 UTC, mmmavis commented
@jhonatan-lopes I've updated the PR according to your suggestions. 😄

2023-08-14 15:36 UTC, jhonatan-lopes approved these changes
Thanks @mmmavis! I've tested this locally and it's working well. I took the liberty to reorder the migrations to be able to merge it though

2023-08-14 16:32 UTC, merged