[WIP] PNI Consumer Creep-O-Meter Page Hero
MozillaFoundation/foundation.mozilla.org pull request #11146
Opened 2023-09-20 19:42 UTC by mmmavis

# Description

Link to sample test page:
Related PRs/issues: #

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2023-09-22 17:13 UTC, tessheinricks requested changes
Looks great Mavis! 

For mobile, are you able to:
- Revise Creep-O-Meter rating speech bubble to have corner radius of 8 instead of 16
- Revise the vertical spacing between the asterisk in the top right and the header copy to be 8 [M_Vertical-Gap_Quaternary]  

Thank you!

2023-09-22 18:32 UTC, mmmavis commented
Hi @tessheinricks , thanks for reviewing. I've made the styling tweaks and the page is ready for review again!

2023-09-22 19:24 UTC, tessheinricks requested changes
Thank you for those revisions Mavis! 

I am wondering if there is any way that the asterisk placement on desktop can more closely reflect the figma file (with the illustration bleeding past where the screen ends on the right), which will give a bit more space to the headline?

Please let me know if you have any questions, or if this would present challenges timeline or development wise. Thanks again!

2023-09-22 19:31 UTC, mmmavis commented
Hi @tessheinricks 

> I am wondering if there is any way that the asterisk placement on desktop can more closely reflect the figma file (with the illustration bleeding past where the screen ends on the right), which will give a bit more space to the headline?

Currently, it's bleeding outside of the "container:

<img width="1657" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/8c088919-933c-4c18-b12a-abfbaaa99d73">

If we want to place the illustration further right to so it bleeds past the viewport I can def do it. However, this means there will be huge gap on larger screen sizes. e.g., 

<img width="1284" alt="image" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/4450d4bf-d225-487d-9a50-0d8daf17bc36">

Let me know which you prefer and I'll adjust the code accordingly. Thanks!

2023-09-22 20:02 UTC, tessheinricks commented
@mmmavis okay amazing thank you for clarifying! I think leaving it how it is now (bleeding outside of the Content Container) is a better solution than the gap! 

If possible, it might be helpful to extend the horizontal spacing gap between the headline and the asterisk to 40 but again, if there is not enough time, no worries!

2023-09-22 20:11 UTC, mmmavis commented
> If possible, it might be helpful to extend the horizontal spacing gap between the headline and the asterisk to 40 but again, if there is not enough time, no worries!

Hi @tessheinricks , we'll have to address this at a later stage. I just tested it out with 40px gap but the illustration would become too cut off to be recognized (in my opinion).

https://github.com/MozillaFoundation/foundation.mozilla.org/assets/2896608/2bafc6dd-f845-46c5-94e3-bf93a7b7f76a

2023-09-22 20:15 UTC, tessheinricks commented
@mmmavis Agreed! Thank you for taking the time to test! We can keep it at the 16px [D_Horizontal-Gap_Primary] variable value for now. 👍

2023-09-22 20:18 UTC, tessheinricks approved these changes
Development looks great!

Design team is keeping additional refinement notes in a separate [word doc](https://docs.google.com/document/d/1LoehvJXp3yIyMM39IDThNIA2attLj8gfo5JomwmCN2g/edit?usp=sharing) for final adjustments.

2023-09-22 20:22 UTC, mmmavis commented on network-api/networkapi/wagtailpages/migrations/0105_consumercreepometerpage.py
>  # Generated by Django 3.2.21 on 2023-09-22 17:40
linting fixes

2023-09-25 18:14 UTC, danielfmiranda approved these changes
Looks great! Thank you Mavis 🙌 approved!

2023-09-25 18:39 UTC, merged