WIP: Donate Help Page FA Form first pass
MozillaFoundation/foundation.mozilla.org pull request #11306
Opened 2023-10-24 19:34 UTC by danielfmiranda

# Description

Link to sample test page:
Related PRs/issues: #11173

2023-10-25 21:56 UTC, mmmavis requested changes
Hey @danielfmiranda , 

At a glance it's not possible to tell what code is copied from FormAssembly vs our own custom code so it's tricky to do code review. Could you mimic what we have for petition form ([formassembly_body.html](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_body.html#L3-L48) and [formassembly_head.html](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_head.html#L3-L26)) and add notes to the top of the two FA related files? Having notes/instructions will also help future code edits from breaking the form.

We'll also need to edit default CSP values on various files for recaptcha to work!

Thanks!

2023-10-26 03:11 UTC, danielfmiranda commented on network-api/networkapi/templates/donate/fragments/formassembly_body.html
> +
Hi @mmmavis just calling out this custom localization JS that I found from Mia and the thunderbird team. I am probably going to have to update this in my localization PR as they are referencing locales we do not use on the foundation site (ex: en-US, es-MX, etc.).

2023-10-26 03:16 UTC, danielfmiranda commented
Hi @mmmavis! Thanks for the review. 

I have updated this PR with what we discussed on slack which includes:
- Updated env.default to include the URLs needed to render the form / recaptcha
- Some comments at the top of the files, which will be updated as I make more changes to the form such as styling/localization


This pr is now ready for re-review whenever you find a free moment. Thanks!

2023-10-27 16:59 UTC, mmmavis requested changes
Looking great! If we can update CSP configs in `app.json` and `continous-integration.yml` as well, that'd be rad 💯

2023-10-27 18:31 UTC, danielfmiranda commented
Thanks for the review @mmmavis! Just updated both `app.json` and `continuous-integration.yml` 👍

2023-10-27 18:32 UTC, mmmavis approved these changes
💯

2023-10-27 18:42 UTC, merged