11582 Fix html validation errors PNI homepage
MozillaFoundation/foundation.mozilla.org pull request #11608
Opened 2023-12-22 21:43 UTC by tbrlpld

# Description

This PR fixes 15 HTML validation errors and 1 HTML validation warning on the PNI homepage. 

There are still 3 errors and 1 warning outstanding. The efforts required for those fixes seemed to large to include in this PR as they might necessitate full component refactors. Follow-up tickets have been filed (#11605, #11606 and #11607). 

Link to sample test page:
Related PRs/issues: #11582

# Checklist

**Tests**
- [x] Is the code I'm adding covered by tests?

**Changes in Models:**
- [-] Did I update or add new fake data?
- [-] Did I squash my migration?
- [x] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [-] Is my code documented?
- [-] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2023-12-22 21:56 UTC, tbrlpld commented on network-api/networkapi/templates/fragments/buyersguide/pni_mobile_nav.html
> +                            <span class="active-link-label d-inline-block multipage-link active">
Converted divs to spans

2023-12-22 21:56 UTC, tbrlpld commented on network-api/networkapi/templates/fragments/buyersguide/pni_mobile_nav.html
> -                                <div>
Removed empty wrappers

2023-12-22 21:59 UTC, tbrlpld commented on network-api/networkapi/templates/fragments/buyersguide/pni_mobile_search.html
> +                    name="search"
For better announcement when the placeholder is overridden / a value is entered.

2023-12-22 21:59 UTC, tbrlpld commented on network-api/networkapi/templates/fragments/buyersguide/pni_sort_dropdown.html
> -    <li aria-expanded="false" role="list" class="tw-absolute tw-top-0 tw-hidden tw-left-0 medium:tw-left-auto medium:tw-right-0 pni-creepiness__list-container tw-w-full medium:tw-w-max tw-z-50 tw-bg-
Invalid role

2023-12-22 21:59 UTC, tbrlpld commented on network-api/networkapi/templates/fragments/buyersguide/primary_nav.html
> +                   aria-label="Search input toggle"
So make the use a bit clearer.

2023-12-22 21:59 UTC, tbrlpld commented on network-api/networkapi/templates/pages/buyersguide/catalog.html
> +        <style>
`noscript` with nested `style` is only valid in the header.

2023-12-22 21:59 UTC, tbrlpld commented on network-api/networkapi/templates/pages/buyersguide/catalog.html
> -                            <input type="checkbox" id="product-filter-pni-toggle" autocomplete="off">
Invalid attribute

2023-12-22 21:59 UTC, tbrlpld commented on source/images/buyers-guide/asterisk-mini.svg
Fixed typo

2024-01-03 00:02 UTC, danielfmiranda requested changes
Hi @tbrlpld!

Thanks very much for taking this work on, after taking a look through the code changes, all updates make sense to me!

However, I did notice that on my local machine and on a [review app](https://foundation-s-11582-fix--lezajp.herokuapp.com/en/privacynotincluded/), it appears that the mobile dropdown navigation has stopped working.


If you could get it working again, I would be happy to approve this PR and the rest of the code changes! If I had to guess, it would be something related to the JS. If you need help or would like to pair-program through this, let me know and I would be happy to help where I can 👍

2024-01-03 15:53 UTC, tbrlpld commented
> Hi @tbrlpld!
> 
> Thanks very much for taking this work on, after taking a look through the code changes, all updates make sense to me!
> 
> However, I did notice that on my local machine and on a [review app](https://foundation-s-11582-fix--lezajp.herokuapp.com/en/privacynotincluded/), it appears that the mobile dropdown navigation has stopped working.
> 
> If you could get it working again, I would be happy to approve this PR and the rest of the code changes! If I had to guess, it would be something related to the JS. If you need help or would like to pair-program through this, let me know and I would be happy to help where I can 👍

Thanks for the review @danielfmiranda. Yea, I noticed the issue with the category dropdown as well. However, this was already present in the `2023-eoy` branch before my changes. I have filed this [bug fix ticket](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11604) to deal with that.

2024-01-03 17:33 UTC, merged