[WIP] 11406 newsletter signup error handling
MozillaFoundation/foundation.mozilla.org pull request #11910
Opened 2024-02-26 19:06 UTC by robdivincenzo

# Description

Link to sample test page:
Related PRs/issues: #11406 

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2024-03-06 00:26 UTC, mmmavis requested changes
PR is working well. Thanks @robdivincenzo ! 

Two little things - 

- There are some comments in `with-submission-logic.jsx` that can be removed.
- Regarding the error message, do you think we can change it to something more generic? `Signup was not created.` and  `Unable to resolve signup.` feel quite technical and not so user friendly in my opinion. Maybe we can ask in the team channel to brainstorm copy ideas? 👀

2024-03-06 00:26 UTC, mmmavis commented on source/js/components/newsletter-signup/organisms/with-submission-logic.jsx
>          // [TODO] We will need to update this logic depending on what comes out of
This comment can finally be removed :D

2024-03-06 00:36 UTC, mmmavis requested changes
For localization, we are moving away from using `getText` as it's reading hardcoded strings in `source/js/components/petition/locale-strings.jsx` and not hooked up with our localization flow. I wonder if there's a way to expose the new strings (the two error messages we are adding in this PR) to Pontoon and have our backend to [send back the localized error message directly](https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/campaign/views.py#L99-L102) ? @jhonatan-lopes @danielfmiranda

2024-03-06 19:13 UTC, jhonatan-lopes commented
Hey @mmmavis! Localisation on JS is handled by serving `.mo` files to the client (see https://docs.djangoproject.com/en/4.2/topics/i18n/translation/#internationalization-in-javascript-code).

We have that enabled on our codebase already. See:

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/bf8bd1d4116b5162e087742cd6d8cf85d7854db0/network-api/networkapi/urls.py#L120

and

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/bf8bd1d4116b5162e087742cd6d8cf85d7854db0/network-api/networkapi/templates/pages/base.html#L135

It seems that from the JS perspective, you just need to call `gettext`, which will then issue a request to the server to fetch the relevant `.mo` file.

We are also prepared to generate messages from JS files:

https://github.com/MozillaFoundation/foundation.mozilla.org/blob/bf8bd1d4116b5162e087742cd6d8cf85d7854db0/tasks.py#L33-L45

I believe that covers all cases but if we have any further questions, I suggest getting in contact with Théo to confirm.

2024-03-07 21:36 UTC, robdivincenzo commented on source/js/components/newsletter-signup/organisms/with-submission-logic.jsx
>          // [TODO] We will need to update this logic depending on what comes out of
You got it! 👍

2024-03-07 21:55 UTC, robdivincenzo commented
@mmmavis @jhonatan-lopes Thanks for all the extra context related to localization!

Interestingly, I do not see strings exporting from JS, only from django (i.e through `blocktrans`). Though `makemessages` is running the correct `-d djangojs` parameter.

I'm tempted to include a hardcode `getText` string for this issue, but spin off a separate issue related just to looking at JS localization. I could use the already translated "Something went wrong" string from `source/js/components/petition/locale-strings.jsx` which would also address the error message being too technical. Thoughts?

2024-03-07 22:14 UTC, jhonatan-lopes commented
Hey @robdivincenzo, are you running `inv makemessages`? If so, could this be broken due to #11825?

2024-03-07 23:03 UTC, robdivincenzo commented
Hey @jhonatan-lopes! Yes, that's the command I ran to check for detecting JS strings. I was also using the updated command from that related issue's [PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/12019). I could verify the .po files updated with a new Django string but not a new JS string. Is there an additional step in the workflow?

2024-03-08 13:26 UTC, jhonatan-lopes commented
:thinking: that's really weird. We can check if it worked before on main but from a Django perspective it seems like everything is in order.

2024-03-14 16:08 UTC, robdivincenzo commented
Based on slack discussions, we're going to approach it the old, hard-coded way to unblock this issue. We'll spin off a separate issue to look at djangojs and a second ticket to refactor this component's localization. We are also going with "Something went wrong and your signup wasn't completed. Please try again later." for the less technical error message per this slack convo: https://mozilla.slack.com/archives/C04DYP6T6VD/p1710357586006909

2024-03-15 16:36 UTC, robdivincenzo commented
Hey @TheoChevalier, we have some hard-coded localized strings in this PR. Can you review the new translations located in `locale-strings.jsx`? Thank you!

2024-03-20 17:22 UTC, TheoChevalier commented
Hi @robdivincenzo, I can get these translated by our translation agency alongside another project (hoping to be able to submit it later today or tomorrow)

Regarding your earlier question about using `window.gettext("My string.")` in jsx files, we just need to make this small change to the makemessages command in tasks.py:

<img width="343" alt="Capture d’écran 2024-03-20 à 18 15 35" src="https://github.com/MozillaFoundation/foundation.mozilla.org/assets/1294206/7369f3c9-da97-474a-85bb-3b7f650fa9d9">

I’ve tried locally and was able to extract your string. The only caveat is that gettext doesn’t support backticks.

2024-03-25 12:51 UTC, TheoChevalier requested changes
Hey @robdivincenzo added the updated translations

2024-03-25 12:51 UTC, TheoChevalier commented on source/js/components/petition/locale-strings.jsx
> +      "Es ist ein Fehler aufgetreten und Ihre Anmeldung wurde nicht abgeschlossen. Bitte versuchen Sie es später noch einmal.",
```suggestion
      "Etwas ist schiefgelaufen und Ihre Anmeldung konnte nicht durchgeführt werden. Bitte versuchen Sie es erneut.",
```

2024-03-25 12:51 UTC, TheoChevalier commented on source/js/components/petition/locale-strings.jsx
> +      "Algo salió mal y tu registro no se completó. Por favor, inténtelo de nuevo más tarde.",
```suggestion
      "Algo salió mal y tu registro no se ha completado. Vuelve a intentarlo más tarde.",
```

2024-03-25 12:51 UTC, TheoChevalier commented on source/js/components/petition/locale-strings.jsx
> +      "Quelque chose s'est mal passé et votre inscription n'a pas été finalisée. Veuillez réessayer plus tard.",
```suggestion
      "Quelque chose s’est mal passé et votre inscription n’a pas été finalisée. Veuillez réessayer plus tard.",
```

2024-03-25 12:51 UTC, TheoChevalier commented on source/js/components/petition/locale-strings.jsx
> +      "Coś poszło nie tak i Twoja rejestracja nie została ukończona. Spróbuj ponownie później.",
```suggestion
      "Coś poszło nie tak i rejestracja nie została ukończona. Spróbuj ponownie później.",
```

2024-03-25 12:51 UTC, TheoChevalier commented on source/js/components/petition/locale-strings.jsx
> +      "Algo deu errado e sua inscrição não foi concluída. Por favor, tente novamente mais tarde.",
```suggestion
      "Algo deu errado e sua assinatura não foi concluída. Tente novamente mais tarde.",
```

2024-03-25 14:13 UTC, TheoChevalier approved these changes
Thanks, looks good to me!

2024-03-26 17:25 UTC, mmmavis approved these changes
Yay! Thanks for the awesome work, @robdivincenzo !

2024-03-26 20:52 UTC, merged