[WIP] Feature/main nav/animation
MozillaFoundation/foundation.mozilla.org pull request #12260
Opened 2024-04-26 21:25 UTC by mmmavis

# Description

Link to sample test page:
Related PRs/issues: #

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2024-04-30 20:37 UTC, sabrinang requested changes
**Desktop**
- When moving from one item to another, I think there is a quick fade/ease out that makes it look like there's a bit of background flashing through going on _(this could be simplified)_

**Tablet**
- Line below navigation disappears after opening item like “who we are” or after when other items snap to top
- Border reappears when closing but items do not reset so top item (so “who we are” gets hidden) appears fully hidden 
- The snap to top is working inconsistently for me, but mainly “Blog” moves up a bit more all the time while the others often stay in place which makes it feel inconsistent/unpredictable

**Mobile**
- When closing a section other than the first section, a strip is seen of “who we are” but does not fully reset back to the top

I’m thinking overall, having close/open animation without snap to top would provide a more predictable/consistent experience

2024-04-30 21:25 UTC, nancyt1 commented
**Mobile**
- Would we be able to animate the initial open and close of the menu? 
- I also noticed that when a nav item is open but i haven't clicked on anything and I close the whole menu, after opening it again the original nav item is still opened. Should we reset once someone closes the menu? 
- +1 to sabrinas comment about not doing snap to top to be more predictable

2024-05-01 16:58 UTC, sabrinang commented
The tablet/mobile issues resolved with removing the snap to top combo. Wanted to check in on desktop, if it was possible to not have the background flashing through when transitioning from one primary nav item to another?

2024-05-01 19:51 UTC, mmmavis commented on source/js/components/accordion/accordion.js
> +      let open = this.title.getAttribute("aria-expanded") === "true";
Checking `aria-expanded` instead as mobile nav doesn't use `tw-hidden` to toggle visibility.

2024-05-01 19:53 UTC, mmmavis commented on source/js/components/nav/mobile-dropdown.js
> -    super.open();
Summary of changes in this file:

- Adding sliding effect by animating section's height
- We've decided to allow multiple open accordions at the same item. There's no longer needs to reset sibling sections.

2024-05-01 19:56 UTC, nancyt1 approved these changes

2024-05-01 19:56 UTC, sabrinang approved these changes

2024-05-01 19:58 UTC, mmmavis commented on source/sass/components/primary-nav.scss
> +      height: auto;
I can't wait to get rid of this file once we fully phase out the old nav 😂

2024-05-02 13:13 UTC, robdivincenzo approved these changes
LGTM 🚀. And very clear comments 📝, thanks Mavis!

2024-05-02 16:22 UTC, merged

2024-05-23 22:25 UTC, data-sync-user commented
➤ Simon Acosta Torres commented:

PR has already been merged.