Add Custom Privacy Text Option to CTAs
MozillaFoundation/foundation.mozilla.org pull request #12293
Opened 2024-05-01 20:10 UTC by robdivincenzo

# Description

This PR adds a field to CTAs to overwrite the default privacy notice. This new field will allow users to A/B test custom privacy text vs. the default privacy text on various signups or petitions.

When this field is set, it will display instead of the default privacy notice. When this field is empty (as by default), the default privacy text will display.

Link to sample test page:
Related PRs/issues: #

# Checklist

**Tests**
~~- [ ] Is the code I'm adding covered by tests?~~

**Changes in Models:**
~~- [ ] Did I update or add new fake data?~~
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
~~- [ ] Is my code documented?~~
~~- [ ] Did I update the READMEs or wagtail documentation?~~

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2024-05-13 20:38 UTC, mmmavis commented
Sorry for the delay. I will review this PR today.

2024-05-13 23:10 UTC, mmmavis requested changes
Yay we are almost ready to enable A/B test for newsletter signup form! I've left some inline comments, please let me know what you think! After searching for all instances of `newsletter-signup-module`, I've also noticed there are a few instances missing the `data-cta-privacy-notice` attribute. For example, in `bannered_campaign_page.html` around line 65, `network-api/networkapi/templates/fragments/primary_nav.html` around line 85, and maybe some more. Could we please add the attribute to those places? Thanks!

2024-05-29 18:02 UTC, robdivincenzo commented on source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
> +  ctaHeader: PropTypes.string,
De-duped! 😅

2024-05-29 18:02 UTC, robdivincenzo commented on source/js/components/newsletter-signup/organisms/default-layout-signup.jsx
> +    //[TODO] Investigate removing the legacy richtext template which renders an empty rich-text div wrapper
Sounds good to me, I've moved the logic 👍

2024-05-29 18:04 UTC, robdivincenzo commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_body.html
> +                <label id="tfa_492-L" class="label preField" aria-label="Privacy Agreement  required">Privacy Agreement</label><br><div class="inputWrapper"><span id="tfa_492" class="choices vertical
Oh wow, that's good to know. Looks like there's a bit of work to make all of this work again when there's a new version. Moved the rules to the override!

2024-05-29 18:05 UTC, robdivincenzo commented
Thanks for the review and feedback @mmmavis! PR should be up-to-date.

2024-05-30 21:59 UTC, mmmavis commented on network-api/networkapi/wagtailpages/templates/wagtailpages/fragments/formassembly_body.html
> +                <label id="tfa_492-L" class="label preField" aria-label="Privacy Agreement  required">Privacy Agreement</label><br><div class="inputWrapper"><span id="tfa_492" class="choices vertical
Yea. It's a lot of manual work involved each time. 😬 🙈

2024-05-30 23:54 UTC, mmmavis approved these changes
@robdivincenzo R+! Awesome work! Before you merge this PR, could you please add a note at the top of `wagtailpages/fragments/formassembly_body.html` about the changes you applied to the privacy field?

2024-05-31 15:17 UTC, merged

2024-06-07 14:36 UTC, data-sync-user commented
➤ Simon Acosta Torres commented:

PR has been merged.