Remove .localized property inside the blog_index_feature template
MozillaFoundation/foundation.mozilla.org pull request #12428
Opened 2024-06-04 18:26 UTC by AdalbertoMoz

# Description

The following changes are related to removing the `.localized` property inside the `blog_index_feature.html` template. The following elements inside the template have to be reviewed to confirm that it's working as expected:
- **Blog Title and Description** for both First Blog shown (on the Index Blog Page) and Featured Video Post.
- **Anchor Tag on Image** for First Blog shown (on the Index Blog Page).

Example of First Blog shown (on the Index Blog Page):
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/169944061/27aa01ab-3ac7-4ac9-bde2-2bf347bf43e3)

Example of Featured Video Post:
![image](https://github.com/MozillaFoundation/foundation.mozilla.org/assets/169944061/f6d2e556-7fac-41f4-a53e-7c6212c77b4b)

Link to sample test page:
Related PRs/issues: #10005

# Checklist

~~**Tests**~~
~~- [ ] Is the code I'm adding covered by tests?~~

~~**Changes in Models:**~~
~~- [ ] Did I update or add new fake data?~~
~~- [ ] Did I squash my migration?~~
~~- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?~~

~~**Documentation:**~~
~~- [ ] Is my code documented?~~
~~- [ ] Did I update the READMEs or wagtail documentation?~~

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2024-06-04 22:40 UTC, danielfmiranda requested changes
Hi @AdalbertoMoz!

Thank you for your work on this PR, it looks great! I've followed the instructions in the description and can confirm that the review app is working as expected.

However, I believe we can simplify the code further by removing the use of `.specific` entirely, as it appears it is no longer needed.

In Wagtail, the `.specific` method returns pages as their most specific subclass. For example, when using `page.get_ancestors()` or `page.get_children()`, the results are returned as a list of the base `Page` model. This prevents access to any subclass-specific methods or properties, such as a `BlogPage`'s `get_meta_image` method or `topics` property, both of which we are accessing in the updated template.
 
I have tested the `localised_featured_pages`and `localised_featured_video_post`methods  locally, and confirmed they both already return querysets of `BlogPage`s. Therefore, using `.specific` is unnecessary, and we can avoid a few additional DB queries by removing it. 👍 

Thanks again for your hard work!

2024-06-04 22:40 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py
> +            page.specific for page in localize_queryset(featured_blog_pages, preserve_order=True)
```suggestion

        localised_featured_blog_pages = [
            page for page in localize_queryset(featured_blog_pages, preserve_order=True)
```

2024-06-04 22:40 UTC, danielfmiranda commented on network-api/networkapi/wagtailpages/pagemodels/blog/blog_index.py
> +        featured_post.blog_page = featured_post.blog_page.localized.specific
```suggestion
        featured_post.blog_page = featured_post.blog_page.localized
```

2024-06-04 22:49 UTC, AdalbertoMoz commented
Hey @danielfmiranda thank you for your comment related to the `specific` property, makes totally sense and removing it makes a small improvement that can add up in the long run!

Just deleted the changes related to the `blog_index.py` file to keep it unchanged.

Could you please review once again the PR and the Review app to confirm everything works as expected?

Again, thanks in advance for your great help! 🙌

2024-06-04 23:10 UTC, danielfmiranda approved these changes
Thanks @AdalbertoMoz! LGTM 🚀

2024-06-05 15:56 UTC, merged

2024-06-07 14:31 UTC, data-sync-user commented
➤ Simon Acosta Torres commented:

PR has been merged.