Tp1 1033 migrate ga to gtm
MozillaFoundation/foundation.mozilla.org pull request #12744
Opened 2024-08-28 19:56 UTC by dlopezvsr

# Description

This PR updates all code snippets using `ReactGA.event({})` and replace them for `window.dataLayer.push({})` adding also the `event` property to the object, which is handled by GTM to identify the event when triggered. Also next to each code update, a trigger and tag is created inside of GTM in order to push the data properly to GA4. 

Link to sample test page:
Related PRs/issues: #

# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

2024-09-03 19:41 UTC, dlopezvsr commented on network-api/networkapi/templates/pages/base.html
> +            <<meta name="gtm-identifier" content="GTM-PQQ8H6PM">
Great catch @ramram-mf, I just corrected on this last commit. Thank you! 😄

2024-09-03 20:22 UTC, ramram-mf approved these changes
LGTM. Thanks Diego

2024-09-03 20:22 UTC, ramram-mf commented on network-api/networkapi/templates/pages/base.html
> +            <<meta name="gtm-identifier" content="GTM-PQQ8H6PM">
Thanks. Let's QA this!

2024-09-03 23:11 UTC, danielfmiranda requested changes
Hi @dlopezvsr !

Great work on this PR, the code changes are looking good and I appreciate the effort you've put into this!

There's just one small adjustment needed regarding the inline scripts.

We use a nonce in our CSP settings to ensure that only scripts we explicitly allow can run on our pages. 

I noticed that the scripts added don't yet include a nonce. To maintain our security standards, could you please update these to include it? This would look something like:

```Javascript
<script nonce="{{ request.csp_nonce }}">window.dataLayer = window.dataLayer || [];</script>
```



Let me know if you have any questions or need further clarification. I'm happy to help!

2024-09-04 15:20 UTC, dlopezvsr commented
@danielfmiranda thank you so much for the very important observation, I just pushed a new commit with the `request.csp_nonce` template inside of the inline script. 

Let me know in case you have other comments 🙌 😄

2024-09-10 00:42 UTC, danielfmiranda approved these changes
LGTM!

2024-09-10 17:57 UTC, merged